import { ByteWriter, crc32, crc32Step, seeded, utf8 } from "./bytes";
import { deflateRaw } from "./deflate";

/** A wall-clock moment written literally, since generated bytes must not depend on today. */
export type DosMoment = { year: number; month: number; day: number; hour?: number; minute?: number };

export type ZipInput = {
  /** Forward slashes; a trailing slash makes a directory entry. */
  name: string;
  data?: Uint8Array | string;
  modified: DosMoment;
  /** Already-compressed media gains nothing from DEFLATE, so real archivers store it. */
  store?: boolean;
  /** Seals the entry with traditional PKWARE encryption, the cipher every unzip still reads. */
  password?: string;
};

const METHOD_STORED = 0;
const METHOD_DEFLATE = 8;
const FLAG_ENCRYPTED = 0x0001;
const DOS_DIRECTORY = 0x10;

function dosDate(moment: DosMoment): number {
  return ((moment.year - 1980) << 9) | (moment.month << 5) | moment.day;
}

function dosTime(moment: DosMoment): number {
  return ((moment.hour ?? 0) << 11) | ((moment.minute ?? 0) << 5);
}

/**
 * Traditional PKWARE ("ZipCrypto") encryption. It is broken as security and was never
 * meant to be more than a lock on a diary here: the demo archive ships a sealed entry
 * whose password is hidden elsewhere in the demo filesystem.
 */
function zipCrypto(plain: Uint8Array, password: string, checkByte: number, seed: number): Uint8Array {
  const keys = [0x12345678, 0x23456789, 0x34567890];
  const update = (byte: number): void => {
    keys[0] = crc32Step(keys[0], byte);
    keys[1] = (Math.imul((keys[1] + (keys[0] & 0xff)) >>> 0, 134_775_813) + 1) >>> 0;
    keys[2] = crc32Step(keys[2], keys[1] >>> 24);
  };
  const stream = (): number => {
    const temp = (keys[2] | 2) & 0xffff;
    return (Math.imul(temp, temp ^ 1) >>> 8) & 0xff;
  };
  for (const byte of utf8(password)) update(byte);

  // Twelve header bytes: eleven of salt and one that lets a reader check the password.
  const random = seeded(seed);
  const header = Array.from({ length: 11 }, () => random.int(256));
  header.push(checkByte);

  const sealed = new Uint8Array(12 + plain.length);
  [...header, ...plain].forEach((byte, index) => {
    sealed[index] = byte ^ stream();
    update(byte);
  });
  return sealed;
}

/**
 * Writes a complete ZIP archive: local headers with their data, the central directory,
 * and the end record. The archive viewer only reads the directory at the tail, but the
 * whole file is real, so a desktop user who extracts it gets the files back.
 */
export function makeZip(inputs: ZipInput[], comment = ""): Uint8Array<ArrayBuffer> {
  const out = new ByteWriter();
  const central = new ByteWriter();

  inputs.forEach((input, index) => {
    const isDirectory = input.name.endsWith("/");
    const plain = typeof input.data === "string" ? utf8(input.data) : (input.data ?? new Uint8Array());
    const crc = crc32(plain);
    const method = isDirectory || input.store ? METHOD_STORED : METHOD_DEFLATE;
    const packed = method === METHOD_DEFLATE ? deflateRaw(plain) : plain;
    const payload = input.password ? zipCrypto(packed, input.password, crc >>> 24, crc ^ index) : packed;
    const flags = input.password ? FLAG_ENCRYPTED : 0;
    const version = method === METHOD_DEFLATE || input.password ? 20 : 10;
    const name = utf8(input.name);
    const offset = out.length;

    out.u32le(0x04034b50).u16le(version).u16le(flags).u16le(method)
      .u16le(dosTime(input.modified)).u16le(dosDate(input.modified))
      .u32le(crc).u32le(payload.length).u32le(plain.length)
      .u16le(name.length).u16le(0).bytes(name).bytes(payload);

    central.u32le(0x02014b50).u16le(20).u16le(version).u16le(flags).u16le(method)
      .u16le(dosTime(input.modified)).u16le(dosDate(input.modified))
      .u32le(crc).u32le(payload.length).u32le(plain.length)
      .u16le(name.length).u16le(0).u16le(0).u16le(0).u16le(0)
      .u32le(isDirectory ? DOS_DIRECTORY : 0).u32le(offset).bytes(name);
  });

  const directoryStart = out.length;
  const directory = central.finish();
  const note = utf8(comment);
  out.bytes(directory)
    .u32le(0x06054b50).u16le(0).u16le(0).u16le(inputs.length).u16le(inputs.length)
    .u32le(directory.length).u32le(directoryStart).u16le(note.length).bytes(note);
  return out.finish();
}
